
services:
  caddy:
    image: caddy:latest
    ports:
      - "3903:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

  garage:
    image: dxflrs/garage:v1.3.1
    volumes:
      - ./garage.toml:/etc/garage.toml
